### ISSUE TITLE
Formatar a visualização dos posts no blog

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia-blog-web#10]
A visualização do post não está visualmente boa. Precisa harmonizar mais o layout.

Uma opção que pode ser utilizada como modelo são os posts da Globo.com:
https://globoesporte.globo.com/futebol/times/palmeiras/noticia/noticias-palmeiras-analisa-derbi-goleada-corinthians.ghtml 

- Tamanho do título
- Tamanho do subtítulo
- Coluna de texto mais curta
- Tamanho do texto
- Espaçamento entre linhas
- espaçamento entre parágrafos
- Tamanho das imagens
- Rodapé das imagens

**Comment by luizeboli** [comment]
@nichollasrennah  por favor veja este vídeo com a exemplificação de como inserir legenda para as imagens da forma adequada

https://www.loom.com/share/78bdddacd85e446f960e60844e1ca978
