### ISSUE TITLE
No título não permite ponto de interrogação

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia-blog-web#11]
Quando o título tem o ponto de interrogação aparece a mensagem 404 quando acessa o link do post.

![image](https://user-images.githubusercontent.com/48101231/106285473-4ec76580-6223-11eb-948a-a16a23412662.png)

**Comment by luizeboli** [comment]
Resolvido na API, precisa um novo deploy 👍🏻 

https://github.com/ufersa/plataforma-sabia-blog-api/commit/b29b5966bfbb74dc3e40fb324a545396a62c8d40

**Comment by luizeboli** [comment]
@nichollasrennah vou encerrar essa issue pois já está resolvida, precisa efetuar um novo deploy da api do blog, acho que @mateus4k deve poder ajudar, o Marcus fazia direto pelo servidor.

**Comment by mateus4k** [comment]
cc @mtullyoc ☝️
